version: "3"

services:
  app:
    build: .
    ports:
      - "5173:5173" # map port specified in "vite.config.ts" to a host port
    restart: always
    volumes:
      - ./:/app
      - node_modules:/app/node_modules

volumes:
  node_modules:
